import { Inter } from "next/font/google";
import "../styles/global.css";
import "../styles/login.css";
import "../styles/register.css";
import Provider from "@/components/Provider";
import { AuthProvider } from "../Context/AuthContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </AuthProvider>
  );
}
export default RootLayout;
